React query
Shunkicreate/busdes-kic-web pull request #30
Opened 2023-03-10 16:45 UTC by Shunkicreate

一旦実装を終えた。ベストプラクティスではないと思うけど、見てみてほしい

2023-03-10 17:34 UTC, mercy34mercy requested changes
Reactの思想とかはあんまりわかってないので、プログラミングとして微妙なところを突っ込んでおきました。

2023-03-10 17:34 UTC, mercy34mercy commented on src/App.tsx
> +                                )
IMO 個人的にはmodeってやるなら、"Nextbus","setting","Timetable"もAppコンポーネント内のPrivateな定数として持った方が自然な気はするって書いたけど、if分の可読性が下がるからIMOで

2023-03-10 17:34 UTC, mercy34mercy commented on src/grobalState/selectors/swapBusRoute.tsx
> +}
NITS eslitで怒られてる理由がわかってないけど、可読性だいぶ低いなと感じる。まだこの方がマシのような、、、

```ts

const checkStation = (route: busRouteAtomType) => {
    // debugger; // eslint-disable-line no-debugger
    if (route.fr === "立命館大学前" && route.to !== "立命館大学"){
        return true
    }
    if(route.fr !== "立命館大学前" && route.to === "立命館大学"){
        return true
     }
    return false
}
```

2023-03-10 17:34 UTC, mercy34mercy commented on src/grobalState/selectors/swapBusRoute.tsx
> +    return (returnSta)
Q ()っているん？いるんやったら俺の知識不足やー

2023-03-10 17:34 UTC, mercy34mercy commented on src/grobalState/selectors/swapBusRoute.tsx
> +        return (swappedRoute)
Q ()っているん？いるんやったら俺の知識不足やー

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/SettingModal.tsx
> +            setBusRoute(newRoute)
IMO 文字列""か''か揃えた方がいい気がする。linterとかで無理かな？ここで気づいただけで全体的に統一感ないなと。

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/SettingModal.tsx
> +                            })}
NITS ここはindexがidxですが、同じ実装の次はiなので統一したほうがいいと思う

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/Settings.tsx
> +                })}
NITS　上で書いた通り、俺はidx派かな

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/TimeTable.tsx
> +    }
MUST このロジック関数化した方がいいと思う

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/TimeTable.tsx
> +                {holyday ? ShowOneCategoryDayBusTime(timeTable.holidays) : ShowOneCategoryDayBusTime(timeTable.weekdays)}
FYI あ三項演算子嫌い俺読めないだけ笑

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/TimeTable.tsx
> +    return (addTimeTable)
Q ここも()ついてる。なんでだろ、、

2023-03-10 17:34 UTC, mercy34mercy commented on src/layout/NextThreeBusInfo.tsx
> +            <div className='text-center' key={inputData.approach_infos[selectedline].bus_name}>
NITS selectedline んーなんかselectedbusとかの方があってるような。。。

2023-03-11 02:24 UTC, Shunkicreate commented on src/App.tsx
> +                                )
おれの見解的にはこのページは可読性最優先にしたい。この実装が遅かったりするんなら変更するかな。また機会があればって感じ

2023-03-11 02:25 UTC, Shunkicreate commented on src/grobalState/selectors/swapBusRoute.tsx
> +}
自分でも悩みながら書いてたから助かる。

2023-03-11 02:32 UTC, Shunkicreate commented on src/grobalState/selectors/swapBusRoute.tsx
> +    return (returnSta)
括弧は複数行になるときに必要なんよね
業務でどっち使ってたかちょっと先生に聞いてみてる

2023-03-11 02:32 UTC, Shunkicreate commented on src/grobalState/selectors/swapBusRoute.tsx
> +        return (swappedRoute)
上に同じ

2023-03-11 02:49 UTC, Shunkicreate commented on src/layout/NextThreeBusInfo.tsx
> +            <div className='text-center' key={inputData.approach_infos[selectedline].bus_name}>
これきょへがなおしてるとこや
viaから名前変わって勝手に書き換えちゃってる。コンフリの種。

2023-03-11 02:52 UTC, Shunkicreate commented on src/layout/SettingModal.tsx
> +            setBusRoute(newRoute)
linterに入れてシングルにした

2023-03-11 02:53 UTC, Shunkicreate commented on src/layout/TimeTable.tsx
> +                {holyday ? ShowOneCategoryDayBusTime(timeTable.holidays) : ShowOneCategoryDayBusTime(timeTable.weekdays)}
参考演算子は使うけど、ちょっと書き換えるわ

2023-03-11 03:04 UTC, Shunkicreate commented on src/layout/TimeTable.tsx
> +    }
やる！

2023-03-11 03:06 UTC, Shunkicreate commented on src/lib/api-client.tsx
> +    }
記事のコピペ笑。個人的にはこの書き方いいなーって思ってた。
```
const response = await ApiClient.get<TimeTableResponse>(`/timetable?fr=${fr}&to=${to}`)
```
こんな感じで割とわかりやすく呼び出せる気がするんやけどどう？

2023-03-11 05:32 UTC, mercy34mercy commented on src/App.tsx
> +                                )
遅いとかはないな。

2023-03-11 05:33 UTC, mercy34mercy commented on src/grobalState/selectors/swapBusRoute.tsx
> +    return (returnSta)
なるほ、知らんかった

2023-03-11 05:34 UTC, mercy34mercy commented on src/lib/api-client.tsx
> +    }
いいと思う。errハンドリングがちょいと気になったくらい

2023-03-11 06:02 UTC, mercy34mercy approved these changes

2023-03-11 06:30 UTC, merged